MCU = STM32F103

BOARD = STM32_F103_STM32DUINO

#BOARD = YEHUO_ZNZ_STM32DUINO

# OPT_DEFS += -DBOOTLOADER_STM32DUINO
# BOOTLOADER_TYPE = stm32duino
# Options to pass to dfu-util when flashing
# DFU_ARGS = -d 1EAF:0003 -a 1 -R
# DFU_SUFFIX_ARGS = -v 1EAF -p 0003

RGB_MATRIX_ENABLE = yes

EEPROM_DRIVER = vendor

OLED_ENABLE = yes
OLED_TRANSPORT = i2c
OLED_DRIVER = ssd1306

SRC += usb_init.c kc.c

OPT_DEFS += -DSTM32_DMA_REQUIRED=TRUE

